---
namespace: zarrenspry
name: artifactory_oss
version: 1.0.0
readme: README.md
authors:
  - Zarren Spry <zarrenspry@gmail.com>

description: Installs Artifactory OSS and all required components
license:
  - MIT
license_file: 'LICENSE'

tags:
  - artifactory
  - oss
  - repository

dependencies:
  community.general: ">=4.0.1"
  community.postgresql: ">=1.5.0"
  ansible.posix: ">=1.3.0"

# The URL of the originating SCM repository
repository: https://github.com/drgr33n-vw/zarrenspry.artifactory-oss.git

# The URL to any online docs
documentation: https://github.com/drgr33n-vw/zarrenspry.artifactory-oss.git

# The URL to the homepage of the collection/project
homepage: https://github.com/drgr33n-vw/zarrenspry.artifactory-oss.git

# The URL to the collection issue tracker
issues: https://github.com/drgr33n-vw/zarrenspry.artifactory-oss/issues

build_ignore:
  - .gitignore
  - .idea/**
  - Pipfile*

