---
dependencies: []

galaxy_info:
  author: "Zarren Spry <zarrenspry@gmail.com>"
  description: "This role installs Artifactory OSS onto the node."
  company: Zarren Spry
  issue_tracker_url: TBA
  license: MIT License
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
    - name: Debian
      versions:
        - stretch
        - buster
  galaxy_tags:
    - artifactory
    - jfrog